---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
  - pull_request

steps:
  - name: fetch tags
    image: docker:git
    commands:
      - git fetch --tags
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: build buildbox
    image: docker:git
    commands:
      - apk add --no-cache make
      - make buildbox
    volumes:
      - name: dockersock
        path: /var/run
  - name: vendor dependencies
    image: docker:git
    commands:
      - apk add --no-cache make
      - make vendor
    volumes:
      - name: dockersock
        path: /var/run
  - name: lint
    image: docker:git
    commands:
      - apk add --no-cache make
      - make lint
    volumes:
      - name: dockersock
        path: /var/run
  - name: unit test
    image: docker:git
    commands:
      - apk add --no-cache make
      - make test
    volumes:
      - name: dockersock
        path: /var/run
  - name: build binaries
    image: docker:git
    commands:
      - apk add --no-cache make
      - make build
    volumes:
      - name: dockersock
        path: /var/run
  - name: build containers
    image: docker:git
    commands:
      - apk add --no-cache make
      - make containers
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: publish

trigger:
  event:
  - tag

steps:
  - name: fetch tags
    image: docker:git
    commands:
      - git fetch --tags
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: publish
    image: docker:git
    environment:
      USERNAME:
        from_secret: quay_username
      PASSWORD:
        from_secret: quay_password
    commands:
      - apk add --no-cache make
      - docker login -u="$USERNAME" -p="$PASSWORD" quay.io
      - make publish
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
---
kind: signature
hmac: 19562967eb86cd74334a8d81e759d479fbea9c941f2d11fd45e98dfe4905ea64

...
