---
kind: pipeline
type: kubernetes
name: pr

steps:
  - name: wait for docker
    image: docker
    commands:
      - while [ ! -S /var/run/docker.sock ]; do sleep 1; done
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: lint
    image: docker:git
    commands:
      - apk add --no-cache make
      - make lint
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: start docker
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
