package infra

type Gravity interface {
	Install(InstallCmd) error
	Status() (GravityStatus, error)
	OfflineUpdate(installerUrl) error
	Join(peerAddr, token, role) error
}

func GravityFromInstaller(vm *VM, installerUrl string) (Gravity, error) {
	return nil, nil
}

type InstallCmd struct {
	// Token is secure token which prevents rogue nodes from joining the cluster during installation.
	Token string `validation:"required"`
	// AdvertiseAddr IP address this node should be visible as. This setting is needed to correctly configure Kubernetes on every machine.
	AdvertiseAddr string `validation:"required"`
	// Cluster is Optional name of the cluster. Autogenerated if not set.
	Cluster string
	// Flavor is (Optional) Application flavor. See Application Manifest for details.
	Flavor string
	// K8SConfig is (Optional) File with Kubernetes resources to create in the cluster during installation.
	K8SConfig string
	// PodNetworkCidr is (Optional) CIDR range Kubernetes will be allocating node subnets and pod IPs from. Must be a minimum of /16 so Kubernetes is able to allocate /24 to each node. Defaults to 10.244.0.0/16.
	PodNetworkCIDR string
	// ServiceCidr (Optional) CIDR range Kubernetes will be allocating service IPs from. Defaults to 10.100.0.0/16.
	ServiceCIDR string
}

type GravityStatus struct {
	// Token is secure token which prevents rogue nodes from joining the cluster during installation.
	Token string `validation:"required"`
	// NodesStatus defines nodes in the cluster and their status
	NodeStatus []NodeStatusType
}

type NodeStatusType struct {
	Node
	Status string
}
